### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by caffeine-based-lifeform** [madnight/bitcoin-chart-cli#1]
I get this message after installing as explained in the README, happens also with options or other currencies.

```
[...]/yarn/global/node_modules/bitcoin-chart-cli/index.js:39
const current = async url => (await axios.get(url)).data
                      ^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
```

**Comment by caffeine-based-lifeform** [comment]
Just checked my node version, probably an issue with that. Feel free to close the issue. 👍

**Comment by madnight** [comment]
yup, as the README says: "node 8.0 or higher (need fancy syntax features thats why 8+)"
