### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by notmike-5** [madnight/bitcoin-chart-cli#12]
I have installed `bitcoin-chart-cli` and created a symlink between /usr/bin/nodejs and usr/bin/node. When I run the command `bitcoin-chart-cli` I receive the following error.

/usr/local/lib/node_modules/bitcoin-chart-cli/index.js:3
const { get, defaultTo, map, flow, sortBy, remove, always,
           ^

SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by madnight** [comment]
Hi notmike-5 i think your version of nodejs is to low `node --version`
https://github.com/madnight/bitcoin-chart-cli#requirements

Requirements
* node 8.0 or higher

**Comment by notmike-5** [comment]
True
