### ISSUE TITLE
url error

### ISSUE THREAD

**Issue by Fcl69** [madnight/bitcoin-chart-cli#13]
bitcoin-chart-cli -V
./.nvm/versions/node/v6.11.4/lib/node_modules/bitcoin-chart-cli/index.js:52
const fetchCoinList = async url =>
                            ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by madnight** [comment]
Hi FCl69 i think your version of nodejs is to old: `node --version`
https://github.com/madnight/bitcoin-chart-cli#requirements

You need at least node 8.0 or higher.

**Comment by Fcl69** [comment]
Yeah, thanks, upgrading node worked.
