### ISSUE TITLE
Erhh..Help requisite!

### ISSUE THREAD

**Issue by itsN1X** [madnight/bitcoin-chart-cli#15]
Installs node, Installs chart-cli but then:
```
/usr/local/lib/node_modules/bitcoin-chart-cli/index.js:21
const printCoins = async () =>
                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```
Help @madnight ?

**Comment by kroitor** [comment]
@itsN1X most likely you need to upgrade your node version, as your current version is too old and does not support the modern JavaScript ES6 async/await syntax.

**Comment by madnight** [comment]
@kroitor thx : )
